/* eslint-disable @typescript-eslint/no-unused-vars */
import { UserController } from './swagger/userController'
import { StatsController } from './swagger/statsController'
import { AuthController } from './swagger/authController'
import { CourseController } from './swagger/courseController'
import { IndividualSessionController } from './swagger/individualSessionController'
import { ProgramController } from './swagger/programController'
import { PaymentController } from './swagger/paymentController'
import { ShopController } from './swagger/shopController'
import { OrderController } from './swagger/orderController'
import { CoachingSlotController } from './swagger/coachingSlotController'
import { HealthController } from './swagger/healthController'
import { MetricController } from './swagger/metricController'
